#=============================================================================
# Copyright (C) 2013 Daniel Pfeifer <daniel@pfeifer-mail.de>
#
# Distributed under the Boost Software License, Version 1.0.
# See accompanying file LICENSE_1_0.txt or copy at
#   http://www.boost.org/LICENSE_1_0.txt
#=============================================================================

language: cpp

compiler:
  - clang
  - gcc

env:
  matrix:
    - PROJECT=BoostAccumulators
    - PROJECT=BoostArray

before_install:
  - sudo add-apt-repository -y ppa:purplekarrot/cmake
  - sudo apt-get update
  - sudo apt-get install cmake cmake-data libopenmpi-dev
  - mkdir build
  - ./shallow-clone develop https://github.com/boostorg/boost.git build/boost

script:
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Debug ..
  - cmake --build . --target $PROJECT-test
